# https://taskfile.dev

version: "3"

env:
  CGO_ENABLED: 0
  GOOS: linux

tasks:
  build:
    env:
      GOARCH: amd64
    vars:
      VERSION:
        sh: git describe --tags --always
      COMMIT:
        sh: git rev-parse --short HEAD
      DATE:
        sh: git log -1 --format=%cd --date=format:'%Y-%m-%d'
    cmd: go build -a -gcflags=all="-l -B" -ldflags="-w -s -X main.version={{.VERSION}} -X main.commit={{.COMMIT}} -X main.date={{.DATE}}" -o improv-${GOOS}-${GOARCH} ./cmd

  release:
    vars:
      NEXT_VERSION:
        sh: svu n
    cmds:
      - git tag {{.NEXT_VERSION}}
      - git push origin --tags
