# https://taskfile.dev

version: "3"

env:
  CGO_ENABLED: 0

tasks:
  build:
    cmd: go build -a -gcflags=all="-l -B" -ldflags="-w -s" -o improv_amd64
  build:arm:
    env:
      GOOS: linux
      GOARCH: arm
    cmd: go build -a -gcflags=all="-l -B" -ldflags="-w -s" -o improv_arm .
