# https://taskfile.dev

version: "3"

env:
  CGO_ENABLED: 0
  GOOS: linux

tasks:
  build:
    env:
      GOARCH: amd64
    cmd: go build -a -gcflags=all="-l -B" -ldflags="-w -s" -o improv-${GOOS}-${GOARCH}
