name: Build

on:
  release:
    types: [released]
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: for ${{ matrix.arch }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        os: [linux]
        arch: ["amd64", "arm", "arm64"]
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v4
      with:
        go-version: '>=1.21.1'
    - uses: arduino/setup-task@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
    - run: task build
      env:
        GOARCH: ${{ matrix.arch }}
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ format('improv-{0}-{1}', matrix.os, matrix.arch) }}
        path: 'improv-*'
        retention-days: 5

  release:
    name: Upload to Release
    runs-on: ubuntu-latest
    needs: [build]
    if: startsWith(github.ref, 'refs/tags/')
    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        merge-multiple: true
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: 'improv-*'
